name: test

on:
  push:
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'
  pull_request:
    paths-ignore:
      - 'packages/docs/**'
      - 'packages/playground/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test:types
      - run: pnpm run -r dev:prepare
      - run: pnpm run test:vitest
      - run: pnpm run build
      - run: pnpm run build:dts
      - run: pnpm run test:dts
      - run: pnpm run size

      - uses: codecov/codecov-action@v2
